import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

val versionPropsFile = rootProject.file("app/version.properties")

fun loadVersionProperties(file: File): Properties {
    val props = Properties()
    if (file.exists()) {
        file.inputStream().use { props.load(it) }
    } else {
        props.setProperty("versionCode", "1")
        props.setProperty("versionName", "1.0.1")
    }
    return props
}

fun saveVersionProperties(file: File, props: Properties) {
    file.parentFile?.mkdirs()
    file.outputStream().use { props.store(it, "Auto-generated by Gradle") }
}

val requestedTasks = gradle.startParameter.taskNames.map { it.lowercase() }
val shouldAutoBumpVersion = requestedTasks.any {
    it.contains("assemble") ||
        it.contains("install") ||
        it.contains("bundle") ||
        it.contains("package") ||
        it == "build" ||
        it.endsWith(":build")
}

val versionProps = loadVersionProperties(versionPropsFile)
var autoVersionCode = versionProps.getProperty("versionCode", "1").toIntOrNull() ?: 1
var autoVersionName = versionProps.getProperty("versionName", "1.0.1")

if (shouldAutoBumpVersion) {
    autoVersionCode += 1
    autoVersionName = "1.0.$autoVersionCode"
    versionProps.setProperty("versionCode", autoVersionCode.toString())
    versionProps.setProperty("versionName", autoVersionName)
    saveVersionProperties(versionPropsFile, versionProps)
}

android {
    namespace = "com.example.firstapp"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.example.firstapp.pulse"
        minSdk = 35
        targetSdk = 36
        versionCode = autoVersionCode
        versionName = autoVersionName

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = "11"
    }
    buildFeatures {
        compose = true
    }
}

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.material)
    implementation("androidx.documentfile:documentfile:1.0.1")
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.okhttp)
    implementation(libs.okhttp.logging)
    implementation(libs.okhttp.mockwebserver)
    implementation(libs.okhttp.tls)
    implementation(libs.datastore.preferences)
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}
